### ISSUE TITLE
Implement Relaton CIE

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-cie#1]
* Create Relaton CIE model
* Create relaton-data-cie, which fetches information from the CIE techstreet.com website and also its own page for non-purchased publications.

**Comment by andrew2net** [comment]
> * Create relaton-data-cie, which fetches information from the CIE techstreet.com website and also its own page for non-purchased publications.

@ronaldtse why do we need the relaton-data-cie gem? Why don't we just make the relaton-cie to fetch the information from the CIE?
What do you mean "own page for non-purchased publications"?

**Comment by ronaldtse** [comment]
@andrew2net sorry for the late reply. I suggested relaton-data-cie because it's hard to search identifiers on their site.

It would be easier to have an index at relaton-data-cie and then cache (daily) the information into a way we can easily find the identifiers.

**Comment by andrew2net** [comment]
@ronaldtse do we need to scrape only CIE documents like `CIE 243:2021` or all documents like `IEC 62477-2 Ed. 1.0 b:2018`, `ISO/TR 4808:2021` etc.
There are 634 CIE documents on the site.
The number of all documents is 625,781. It may take several days to scrape all of them.

**Comment by ronaldtse** [comment]
@andrew2net let's only cache the publications on cie.co.at. Only CIE documents. Thanks!

**Comment by andrew2net** [comment]
@ronaldtse there are advisors contributors:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/5623890/109325793-a2df5d00-7856-11eb-8e28-a7f60c468505.png">
which role type should we map to advisor?
```
role =
  element role {
    attribute type { ( "author" | "performer" | "publisher" | "editor" | "adapter" | "translator" | "distributor" ) }?,
    roledescription*
}
```

**Comment by ronaldtse** [comment]
Great find @andrew2net . I think we have to extend the vocabulary to accommodate that.

**Comment by ronaldtse** [comment]
Ping @opoudjis to find the appropriate role. I think `advisor` is acceptable.

**Comment by andrew2net** [comment]
@ronaldtse it seems these documents [016](https://cie.co.at/publications/daylight-0) and [CIE 016-1970](https://cie.co.at/publications/daylight) are identical, aren't they? Should we process them separately?

**Comment by ronaldtse** [comment]
@andrew2net yes the 016 documents are identical. Can we differentiate them? I noticed they have these different links:
* https://cie.co.at/publications/daylight-0
* https://cie.co.at/publications/daylight

We should prioritise the latter since it's cleaner?

The CIE 197:2011 document links are indeed strange. I wonder if they are using some non-standard way to enter these documents.

**Comment by andrew2net** [comment]
@ronaldtse seems this [document](https://cie.co.at/publications/disc-version-cie-photometric-and-colorimetric-data-publ-182-86-s001-and-s002-tables) is just a disc version of some documents. Do we need it in our repo?

**Comment by andrew2net** [comment]
@ronaldtse the pages on the cie.co.at are not structured well. Will try https://www.techstreet.com/cie/searches/31156444

**Comment by andrew2net** [comment]
@ronaldtse there are about 300 documents without identifier like [this one](https://www.techstreet.com/cie/standards/a-real-time-system-to-enhance-legibility-and-awareness-of-text-information-for-an-optical-see-through-hmd-po38-616-625?product_id=2016414). Should store them in our repo? If yes then how to reference such a document?

**Comment by ronaldtse** [comment]
That particular paper seems to have a document identifier of "PO38, 616-625".
<img width="704" alt="Screenshot 2021-03-03 at 11 27 47 AM" src="https://user-images.githubusercontent.com/11865/109748238-7c813f00-7c13-11eb-8817-ab36cba98c26.png">

e.g. this page contains a number of those: https://www.techstreet.com/cie/subgroups/54760

**Comment by ronaldtse** [comment]
Maybe it can be called "CIE PO38, 616-625"

**Comment by andrew2net** [comment]
> Maybe it can be called "CIE PO38, 616-625"

@ronaldtse maybe but then there are documents with same reference. For example [this](https://www.techstreet.com/cie/standards/perception-of-illumination-whiteness-op01-pages-1-7?product_id=1941802) and [this](https://www.techstreet.com/cie/standards/perception-of-illumination-whiteness-op01-pages-1-7?product_id=1941834). It won't be prolem if they were identical but several of them misses some information. The documents I mention above have different authors and one of them lack of description. Maybe we should merge them?

**Comment by ronaldtse** [comment]
@andrew2net yes this is very strange. I don't know how we can reconcile these entries. For these particular documents, simple merging is also difficult since the author names are encoded differently.

I noticed that some "conference proceeding" document on techstreet has a "product code" that is unique:

[First link](https://www.techstreet.com/cie/standards/perception-of-illumination-whiteness-op01-pages-1-7?product_id=1941802):
<img width="353" alt="Screenshot 2021-03-05 at 10 52 08 AM" src="https://user-images.githubusercontent.com/11865/110060411-d6fbd600-7da0-11eb-8cf8-8457f1933281.png">

[Second link](https://www.techstreet.com/cie/standards/perception-of-illumination-whiteness-op01-pages-1-7?product_id=1941834):
<img width="358" alt="Screenshot 2021-03-05 at 10 52 45 AM" src="https://user-images.githubusercontent.com/11865/110060456-ed099680-7da0-11eb-884a-1ceb374d1c8f.png">

`x043` seems to be the conference ID, and the code behind is proceeding ID. Would this ID work as the unique key?

Conference proceedings: [link](https://www.techstreet.com/searches/31266684?action=show&controller=searches&gateway_code=cie&id=31266684&sort_direction=&sort_order=&per_page=50)

But not all Conference Proceedings have this product code, e.g.
[this](https://www.techstreet.com/cie/standards/smart-garnish-light-display-for-visual-assistance-in-automobile-po24-526-533?product_id=2016301)
<img width="257" alt="Screenshot 2021-03-05 at 10 56 25 AM" src="https://user-images.githubusercontent.com/11865/110060793-6f925600-7da1-11eb-913f-0662c0a76b29.png">

**Comment by opoudjis** [comment]
> Ping @opoudjis to find the appropriate role. I think `advisor` is acceptable.

Hold up, hold up, hold up.

````
role =
  element role {
    attribute type { ( "author" | "performer" | "publisher" | "editor" | "adapter" | "translator" | "distributor" ) }?,
    roledescription*
}
````

The type will NOT be extended beyond those seven values. That is a modelling decision inherited from ISO-690. Advisors must be entered in roledescription, as a refinement of a type; and the best fit we have to that is `editor`. So, `<role attribute="editor>advisor</role>`.

**Comment by ronaldtse** [comment]
@opoudjis okay

**Comment by andrew2net** [comment]
@ronaldtse  there are documents like [CIE S 006.1/E-1998 (ISO 16508:1999)](https://www.techstreet.com/cie/standards/cie-s-006-1-e-1998-iso-16508-1999?product_id=1210129).
Should we reference them like CIE S 006.1/E-1998?
Shouldn't the ISO 16508:1999 be a second document id?

**Comment by ronaldtse** [comment]
Yes in these cases they are dual ID documents. If the user cites `CIE S 006.1/E-1998`, we render `CIE S 006.1/E-1998 (ISO 16508:1999)`.

Here's the actual document preview:
https://cdn.standards.iteh.ai/samples/31003/2112810a52ec4b77917c120d7d9741b9/ISO-16508-1999.pdf

Technically this is Dual ID:
<img width="544" alt="Screenshot 2021-03-22 at 9 52 02 PM" src="https://user-images.githubusercontent.com/11865/112000316-d6ad5a00-8b58-11eb-8549-ed1660f327ae.png">

In the case of `CIE S 009 / E:2002 / IEC 62471:2006`, it is also a dual ID:
https://cdn.standards.iteh.ai/samples/15358/5d30e63eeba94e6ab50031932b0d23a1/IEC-62471-2006.pdf

<img width="539" alt="Screenshot 2021-03-22 at 9 53 42 PM" src="https://user-images.githubusercontent.com/11865/112000568-12482400-8b59-11eb-81fc-03cd04ff4add.png">

Notice that the CIE reference number is already different between these two documents:
* year number: `-1998` vs `:2002`
* reference to second ID `(ISO ...)` vs `/ IEC ...`. 

This is also reflected in the normative references:
* first doc: <img width="826" alt="Screenshot 2021-03-22 at 9 59 35 PM" src="https://user-images.githubusercontent.com/11865/112001395-e5e0d780-8b59-11eb-9ead-2a97e20d70fb.png">
* second doc - all older docs use the old year scheme: 
<img width="851" alt="Screenshot 2021-03-22 at 10 00 17 PM" src="https://user-images.githubusercontent.com/11865/112001513-ff821f00-8b59-11eb-82a1-fd9aa4130ec3.png">

For the primary ID, we should allow all these variations: 
* With language `/E`: `CIE S 006.1/E-1998`, `CIE S 009/E:2002`
* Without language `/E`: `CIE S 006.1-1998`, `CIE S 009:2002`

For the second ID, let's use the pattern `{primary id} ({secondary id})`.

Note that if the primary ID contains language, the secondary ID should also contain language. Similarly if the primary ID doesn't contain language, the second ID should not contain language.
